#include<conio.h>
#include<stdio.h>
#include<iostream.h>
void main()
{       clrscr();
	int i,j,num;

	char ch='A';
	char ch1='b';
 //	cout<<"enter the no of rows";
   //	cin>>num;
	cout<<ch;
	cout<<ch1;
	ch1 = ch1 + 1;
	cout<<ch1;
	ch = ch+3;
	cout<<ch;
	ch1 = ch1 +2;
	cout<<ch1;
cout<<"\n";
	for( i=1;i<=5;i++)
	{
	cout<<i;
	}cout<<"\n" ;

		char ch2='A';
	char ch3='b';

	cout<<ch2;
	cout<<ch3;
	ch3 = ch3 + 1;
	cout<<ch3;
	ch2 = ch2+3;
	cout<<ch2;
	ch3 = ch3 +2;
	cout<<ch3;
	cout<<"\n";
	for( i=1;i<=5;i++)
	{
	cout<<i;
}
	getch();
}