#include<stdio.h>
#include<conio.h>
#include<iostream.h>
void main()
{	clrscr();
	int i,j;
	char z;
	for(i=1;i<=2;i++)
	{
		char c1='A';
		cout<<c1;
		for(j=1;j<=1;j++)
		{
			char c2='b';
			cout<<c2;
			c2=c2+1;
			cout<<c2;
		       char c3=c1+3;
			cout<<c3;
			char c4=c2+2;
			cout<<c4;
			cout<<"\n";
			for(int k=1;k<=5;k++)
			{
				cout<<k;
				}

	}  cout<<"\n";}
	getch();
}